name: The KNESTs stack CI/CD

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run e2e tests
        run: |
          whoami
          docker network create knests-test
          addgroup --gid 1000 nodegroup
          adduser node nodegroup
          chown -R node:nodegroup .
          docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build --abort-on-container-exit --renew-anon-volumes --force-recreate